[project]
name = "cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagshub>=0.6.4",
    "dvc>=3.66.1",
    "mlflow>=3.8.1",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.8.0",
]
